version: '3'

services:

  redis:
    image: redis
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  nats:
    image: nats
    container_name: nats_server
    restart: always
    ports:
      - "4222:4222"

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db




